source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'erubis'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'sinatra'
gem 'unicorn'
gem 'redis'
gem 'mysql2-client-general_log', github: 'ABCanG/mysql2-client-general_log', branch: 'writefile'

group :development do
  gem 'foreman'
  gem 'sinatra-contrib', require: nil
  gem 'stackprof'
  gem 'dotenv'
end
